- shell: "export evil='() { :;}; echo vulnerable'; bash -c echo;"
  register: result

- fail:
    msg="Not Vulnerable"
  when: result.stdout != 'vulnerable'

#- command: pkgadd 

- shell: "export evil='() { :;}; echo vulnerable'; bash -c echo;"
  register: result

- fail:
    msg="Still Vulnerable After Applying Patch"
  when: result.stdout == 'vulnerable'
